name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  pull_request:
    branches: second-main
    types: [ opened, edited, reopened, ready_for_review, unlocked, synchronize ]
jobs:
  Is-The-Branch-Updated:
    name: is updated check
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Checking Branch
        uses: Automattic/action-pr-is-up-to-date@v2
      - run: echo "Checkin process is over"